config/routes.rb
Rails.application.routes.draw do
  resources :compras
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:fecha_compra, :monto, :cliente)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_form.html.erb
<%= form_with(model: compra, local: true) do |form| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha_compra %>
    <%= form.date_select :fecha_compra, id: :compra_fecha_compra %>
  </div>

  <div class="field">
    <%= form.label :monto %>
    <%= form.text_field :monto, id: :compra_monto %>
  </div>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.text_area :cliente, id: :compra_cliente %>
  </div>

  <div class="actions">
    <%= form.submit class:"button success"  %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra, class:"button success" %> |
<%= link_to 'Back', compras_path, class:"button" %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Fecha compra</th>
      <th>Monto</th>
      <th>Cliente</th>
      <th>Ver</th>
      <th>Editar</th>
      <th>Eliminar</th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.fecha_compra %></td>
        <td><%= compra.monto %></td>
        <td><%= compra.cliente %></td>
        <td><%= link_to 'Show', compra, class:"button success" %></td>
        <td><%= link_to 'Edit',  edit_compra_path(compra), class:"button secondary" %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, class:"button alert", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<center>
  <%= link_to 'New Compra', new_compra_path, class:"button postfix" %>
</center>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path, class:"button" %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha compra:</strong>
  <%= @compra.fecha_compra %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @compra.monto %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @compra.cliente %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra), class:"button secondary" %> |
<%= link_to 'Back', compras_path, class:"button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Compras" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>